name: "Publish Atividade 1"
on:
  push:
    branches: [atividade-1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Enable emscripten
      - name: Pull emscripten
        run: git clone https://github.com/emscripten-core/emsdk.git 
        
      - name: Build web assembly 
        run: ./emsdk/emsdk install latest && ./emsdk/emsdk activate latest && source ./emsdk/emsdk_env.sh && ./runweb.sh

      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/atividade-1' }} # Publish only when the push is on atividade-1
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: atividade-1
          publish_dir: ./public
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
